baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Olive & Mango"
disqusShortname = "disqus_Ci8qqqEWpn"

[params]
  description = "A budget-conscious lifestyle blog on food, travel, and well-being"


[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
  name = "Home"
  url  = "/"
  weight = 1
[[menu.main]]
  name = "Recipes"
  url  = "/recipes"
  weight = 2
[[menu.main]]
  name = "Blog"
  url  = "/blog"
  weight = 3
[[menu.main]]
  name = "About"
  url  = "/about"
  weight = 4

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
